### ISSUE TITLE
an error run with cuda

### ISSUE THREAD

**Issue by ThreeIcug** [AlTarFramework/altar#33]
Dear author,
      I have installed the altar successfully. But when I  test the example with CUDA setting, it will print error.

$ slipmodel --config=staticCp.pfg 
$ altar: current worker 0 with device <cuda.Device.Device object at 0x7f13ce6d28b0> id 0
CUSOLVER Error 7 at /home/ti/tools/src/pyre/extensions/cuda/cusolver.cc:39

The example of cudalinear  is the same error.

python3 -c 'import pyre'  ， python3 -c 'import cuda'  , python3 -c 'import altar' ，all is OK

nvidia-smi result:

![Screenshot from 2022-08-23 17-08-23](https://user-images.githubusercontent.com/47657302/186119243-497fdc54-44a5-481f-a032-a394f60b91c6.png)

**Comment by lijun99** [comment]
CUDA 11 has dropped support for SM30 devices. You will need to use cuda 10 or switch to a newer generation of gpus.

**Comment by ThreeIcug** [comment]
Thank you. I change it to 10.1 and the example is OK.

**Comment by ThreeIcug** [comment]
I have a question for the
