### ISSUE TITLE
Error: static slip model example (not using cuda)

### ISSUE THREAD

**Issue by aerpearson** [AlTarFramework/altar#35]
I can run the linear model example successfully, so I know I have things working to that extent, but I've been unable to run the static slip model example that's included with the program. I get the following error triggered in Static.py-->loadInputs when it tries to load static.gf.h5, static.data.h5, and static.Cd.h5:
 ** ** ** GSL error: fscanf failed
 ** ** ** GSL error: fscanf failed
 ** ** ** GSL error: fscanf failed
 ** ** ** GSL error: matrix is singular
 ** ** ** GSL error: matrix is not positive definite
The parameters then come out as all zeros and it gives the positive definite error again when it tries to resample.

Using my own data as HDF5 files, the same thing happens. Using my own data as .txt, I can run it without the fscanf failed error (and see under loadInputs that the data did successfully load), but at some point within the code it's back to all zeros and gives the positive definite error when it tries to resample. I think this is different from the previous positive definite issue that was opened because it seems to not be creating any samples and that's why the same error occurs. 

I believe I've made all of the non-cuda adjustments from the reference documentation (switching all .cuda things in the config file, switching strikeslip and dipslip to contiguous), but I also wanted to double-check that this task is possible without an NVIDIA graphics card/access to cuda. Thanks in advance for any insight!

**Comment by lijun99** [comment]
The cpu version of the static slip model needs more work (sorry, it was a leftover). Please use the linear model instead, and use either text or binary (in double precision) input files.

**Comment by aerpearson** [comment]
Thanks, the linear model worked!
